### ISSUE TITLE
code do not work

### ISSUE THREAD

**Issue by 1999kevin** [dman82499/Color_Connected_Components#1]
Hi, I'm searching for such a color connected components code and find this. However, the code in your scc.py do not work. It seems that this file lacks some imported libaray, such as numba and opencv. Could you please complete this part?

Thank you very much.

**Comment by dman82499** [comment]
Hello Kevin,
Thanks for your interest. As you stated, numba and opencv are seperate third party libraries that are available outside of this repository.  As this code is currently written, you will need to install the library yourself for it to work. 

That being said, since this was not very clear I will update setup.py to account for the dependencies, and I will also include import statements in scc.py itself, as it does appear that these were unintentionally left out.

Thanks,

Devan
